---
abstract: 'Sends an email whenever a user connects'
author:
  - 'Nito Martinez <Nito@Qindel.ES>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: QVD-L7R-Authenticator-Plugin-Notifybymail
provides:
  QVD::L7R::Authenticator::Plugin::Notifybymail:
    file: lib/QVD/L7R/Authenticator/Plugin/Notifybymail.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 3.115787
