---
abstract: 'QVD client library'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: QVD-Client
provides:
  QVD::Client:
    file: lib/QVD/Client.pm
    version: 0.01
  QVD::Client::Frame:
    file: lib/QVD/Client/Frame.pm
    version: 0
  QVD::Client::Proxy:
    file: lib/QVD/Client/Proxy.pm
    version: 0
requires:
  Crypt::OpenSSL::X509: 0
  Cwd: 0
  File::Spec: 0
  IO::Socket::Forwarder: 0
  IO::Socket::SSL: 0
  JSON: 0
  MIME::Base64: 0
  Proc::Background: 0
  QVD::Config: 0
  QVD::HTTP: 0
  QVD::HTTPC: 0
  QVD::Log: 0
  Test::More: 0
  URI::Escape: 0
  Wx: 0
  X11::Protocol: 0
  parent: 0
version: 3.3
