---
abstract: lib/QVD/HKD.pm
author:
  - 'QVD Team <qvd@qindel.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: QVD-HKD
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 5.34
  AnyEvent::Pg: 0.12
  AnyEvent::Semaphore: 0.01
  App::Daemon: 0
  Class::StateMachine: 0.23
  Class::StateMachine::Declarative: 0.01
  EV: 4.10
  Fcntl::Packer: 0.02
  File::Slurp: 0
  Linux::Proc::Mountinfo: 0.01
  Pg::PQ: 0.13
  QVD::Config: 0
  QVD::L7R: 0
  QVD::Log: 0
  QVD::VMKiller: 0
version: 3.5
